// Created by iWeb 3.0.4 local-build-20120615

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,34),url:'people_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'people_files/stroke_1.png'},{rect:new IWRect(2,-2,113,4),url:'people_files/stroke_2.png'},{rect:new IWRect(115,-2,4,4),url:'people_files/stroke_3.png'},{rect:new IWRect(115,2,4,34),url:'people_files/stroke_4.png'},{rect:new IWRect(115,36,4,4),url:'people_files/stroke_5.png'},{rect:new IWRect(2,36,113,4),url:'people_files/stroke_6.png'},{rect:new IWRect(-2,36,4,4),url:'people_files/stroke_7.png'}],new IWSize(117,38)),stroke_0:new IWEmptyStroke(),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,8),url:'people_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'people_files/stroke_9.png'},{rect:new IWRect(1,-1,125,2),url:'people_files/stroke_10.png'},{rect:new IWRect(126,-1,2,2),url:'people_files/stroke_11.png'},{rect:new IWRect(126,1,2,8),url:'people_files/stroke_12.png'},{rect:new IWRect(126,9,2,2),url:'people_files/stroke_13.png'},{rect:new IWRect(1,9,125,2),url:'people_files/stroke_14.png'},{rect:new IWRect(-1,9,2,2),url:'people_files/stroke_15.png'}],new IWSize(127,10))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('people_files/peopleMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');fixAllIEPNGs('Media/transparent.gif');IMpreload('people_files','shapeimage_17','0');IMpreload('people_files','shapeimage_20','0');IMpreload('people_files','shapeimage_24','0');applyEffects()}
