// Created by iWeb 3.0.4 local-build-20120615

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,34),url:'pde_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'pde_files/stroke_9.png'},{rect:new IWRect(2,-2,360,4),url:'pde_files/stroke_10.png'},{rect:new IWRect(362,-2,4,4),url:'pde_files/stroke_11.png'},{rect:new IWRect(362,2,4,34),url:'pde_files/stroke_12.png'},{rect:new IWRect(362,36,4,4),url:'pde_files/stroke_13.png'},{rect:new IWRect(2,36,360,4),url:'pde_files/stroke_14.png'},{rect:new IWRect(-2,36,4,4),url:'pde_files/stroke_15.png'}],new IWSize(364,38)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,34),url:'pde_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'pde_files/stroke_1.png'},{rect:new IWRect(2,-2,138,4),url:'pde_files/stroke_2.png'},{rect:new IWRect(140,-2,4,4),url:'pde_files/stroke_3.png'},{rect:new IWRect(140,2,4,34),url:'pde_files/stroke_4.png'},{rect:new IWRect(140,36,4,4),url:'pde_files/stroke_5.png'},{rect:new IWRect(2,36,138,4),url:'pde_files/stroke_6.png'},{rect:new IWRect(-2,36,4,4),url:'pde_files/stroke_7.png'}],new IWSize(142,38)),stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('pde_files/pdeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id26');adjustFontSizeIfTooBig('id26');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id28');adjustFontSizeIfTooBig('id28');adjustLineHeightIfTooBig('id29');adjustFontSizeIfTooBig('id29');adjustLineHeightIfTooBig('id30');adjustFontSizeIfTooBig('id30');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
