// Created by iWeb 3.0.4 local-build-20120615

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,34),url:'research_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'research_files/stroke_1.png'},{rect:new IWRect(2,-2,138,4),url:'research_files/stroke_2.png'},{rect:new IWRect(140,-2,4,4),url:'research_files/stroke_3.png'},{rect:new IWRect(140,2,4,34),url:'research_files/stroke_4.png'},{rect:new IWRect(140,36,4,4),url:'research_files/stroke_5.png'},{rect:new IWRect(2,36,138,4),url:'research_files/stroke_6.png'},{rect:new IWRect(-2,36,4,4),url:'research_files/stroke_7.png'}],new IWSize(142,38))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('research_files/researchMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
